# Generated by Django 4.2.6 on 2023-10-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('diagrams', '0001_initial'), ('diagrams', '0002_alter_molecules_rna_type'), ('diagrams', '0003_alter_molecules_rna_type'), ('diagrams', '0004_alter_molecules_dataset')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datasets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Molecules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rna_type', models.CharField(max_length=25)),
                ('length', models.IntegerField()),
                ('name', models.CharField(max_length=75)),
                ('license_plate', models.CharField(max_length=100)),
                ('unnormalized_read_counts', models.IntegerField()),
                ('dataset', models.CharField(db_index=True, max_length=50)),
            ],
            options={
                'unique_together': {('dataset', 'license_plate')},
            },
        ),
    ]
