# Generated by Django 4.2.6 on 2023-10-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datasets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Molecules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=50)),
                ('rna_type', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('license_plate', models.CharField(max_length=45)),
            ],
            options={
                'unique_together': {('dataset', 'license_plate')},
            },
        ),
    ]
