# Generated by Django 4.2.6 on 2023-10-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0003_alter_molecules_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecules',
            name='length',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='molecules',
            name='unnormalized_read_counts',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
